server:
  port: 80
spring:
  application:
    name: gateway
  cloud:
    # nacos注册中心
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      discovery:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
         - id: test
           predicates:
             - Path=/test
           uri: http://localhost:8767/test
         #
         - id: databasew-web
           predicates:
             - Path=/databasew-web/**
           uri: lb://database
           filters:
             - StripPrefix=1


management:
  endpoints:
    web:
      exposure:
        include:  '*'
